# Generated by Django 4.2 on 2023-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_Qliq_data1", models.IntegerField()),
                ("fact_Qliq_data2", models.IntegerField()),
                ("fact_Qoil_data1", models.IntegerField()),
                ("fact_Qoil_data2", models.IntegerField()),
                ("forecast_Qliq_data1", models.IntegerField()),
                ("forecast_Qliq_data2", models.IntegerField()),
                ("forecast_Qoil_data1", models.IntegerField()),
                ("forecast_Qoil_data2", models.IntegerField()),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                ("date", models.DateField(verbose_name="Дата анализа")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnalysisSumByDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_Qliq_data1", models.IntegerField()),
                ("fact_Qliq_data2", models.IntegerField()),
                ("fact_Qoil_data1", models.IntegerField()),
                ("fact_Qoil_data2", models.IntegerField()),
                ("forecast_Qliq_data1", models.IntegerField()),
                ("forecast_Qliq_data2", models.IntegerField()),
                ("forecast_Qoil_data1", models.IntegerField()),
                ("forecast_Qoil_data2", models.IntegerField()),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
